name=CH32_433Mhz_Library
version=1.0.0
author=Desert Vox
maintainer=YourName <desertvoxchannel@gmail.com>
sentence=A robust density-pulsation library for noisy 433MHz modules.
paragraph=Filters background static noise using an asynchronous time-slice integration window without relying on hardware interrupts or complex timers.
category=Communication
url=https://github.com
architectures=*
